/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import manejadores.manejadorLogin;
import modelos.Usuario;

/**
 *
 * @author ricardo
 */
public class LogIn extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    public LogIn() {
         this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuarioText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        ingresoButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Proyecto Inventarios - CUNOC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 40));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        usuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextActionPerformed(evt);
            }
        });
        getContentPane().add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 150, -1));
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 150, -1));

        ingresoButton.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        ingresoButton.setForeground(new java.awt.Color(1, 1, 1));
        ingresoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ingresarPressed.png"))); // NOI18N
        ingresoButton.setBorder(null);
        ingresoButton.setBorderPainted(false);
        ingresoButton.setContentAreaFilled(false);
        ingresoButton.setFocusPainted(false);
        ingresoButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ingresar.png"))); // NOI18N
        ingresoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ingresoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 50, -1));

        salirButton.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        salirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salirPressed.png"))); // NOI18N
        salirButton.setBorder(null);
        salirButton.setBorderPainted(false);
        salirButton.setContentAreaFilled(false);
        salirButton.setFocusPainted(false);
        salirButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salir.png"))); // NOI18N
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTextActionPerformed

    private void ingresoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoButtonActionPerformed
        
        manejadorLogin login = new manejadorLogin();
        Usuario gerente = new Usuario();
        
        String a = new String(passwordText.getPassword());
            if (!usuarioText.getText().equals("") && !a.equals("") ) {
                gerente.setUsuario(usuarioText.getText());
                gerente.setPassword(a);
            try {
                if (login.loginUsuario(gerente)) {
                    panelAdmin panel = new panelAdmin();
                    panel.setVisible(true);
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Credenciales Incorrectas", "Alerta", JOptionPane.ERROR_MESSAGE);
                    usuarioText.setText("");
                    passwordText.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
                 JOptionPane.showMessageDialog(null, "INGRESE DATOS  ");
            }
    }//GEN-LAST:event_ingresoButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton salirButton;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables

     class FondoPanel extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Images/LogIn.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
