/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ricardo
 */
public class panelAdmin extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    public panelAdmin() {
        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cesionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        usuarioMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        bienesMenu = new javax.swing.JMenuItem();
        inventarioMenu = new javax.swing.JMenuItem();
        trasladosMenu = new javax.swing.JMenuItem();
        reportesMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOBBY DE INVENTARIOS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cesionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salirPressed.png"))); // NOI18N
        cesionButton.setBorder(null);
        cesionButton.setBorderPainted(false);
        cesionButton.setContentAreaFilled(false);
        cesionButton.setFocusPainted(false);
        cesionButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salir.png"))); // NOI18N
        cesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cesionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cesionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 80, 70));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 480));

        jMenuBar1.setBackground(new java.awt.Color(1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(254, 254, 254));

        jMenu1.setBackground(new java.awt.Color(124, 119, 100));
        jMenu1.setText("Administracion");

        usuarioMenuItem.setBackground(new java.awt.Color(1, 1, 1));
        usuarioMenuItem.setForeground(new java.awt.Color(254, 254, 254));
        usuarioMenuItem.setText("Modulo Usuarios");
        usuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(usuarioMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(149, 144, 126));
        jMenu2.setText("Inventario");

        bienesMenu.setBackground(new java.awt.Color(1, 1, 1));
        bienesMenu.setForeground(new java.awt.Color(254, 254, 254));
        bienesMenu.setText("Modulo Bienes");
        bienesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bienesMenuActionPerformed(evt);
            }
        });
        jMenu2.add(bienesMenu);

        inventarioMenu.setBackground(new java.awt.Color(1, 1, 1));
        inventarioMenu.setForeground(new java.awt.Color(254, 254, 254));
        inventarioMenu.setText("Inventario");
        inventarioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioMenuActionPerformed(evt);
            }
        });
        jMenu2.add(inventarioMenu);

        trasladosMenu.setBackground(new java.awt.Color(1, 1, 1));
        trasladosMenu.setForeground(new java.awt.Color(254, 254, 254));
        trasladosMenu.setText("Traslados Internos");
        trasladosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trasladosMenuActionPerformed(evt);
            }
        });
        jMenu2.add(trasladosMenu);

        reportesMenu.setBackground(new java.awt.Color(1, 1, 1));
        reportesMenu.setForeground(new java.awt.Color(254, 254, 254));
        reportesMenu.setText("Reportes");
        reportesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesMenuActionPerformed(evt);
            }
        });
        jMenu2.add(reportesMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bienesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bienesMenuActionPerformed
        bienesForm bienes = new bienesForm();
        bienes.setVisible(true);
    }//GEN-LAST:event_bienesMenuActionPerformed

    private void inventarioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioMenuActionPerformed
        inventarioForm inventario = new inventarioForm();
        inventario.setVisible(true);
    }//GEN-LAST:event_inventarioMenuActionPerformed

    private void usuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMenuItemActionPerformed
        usuarioForm usuario = new usuarioForm();
        usuario.setVisible(true);
    }//GEN-LAST:event_usuarioMenuItemActionPerformed

    private void cesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cesionButtonActionPerformed
        LogIn panel = new LogIn();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cesionButtonActionPerformed

    private void trasladosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trasladosMenuActionPerformed
       trasladosForm traslados = new trasladosForm();
       traslados.setVisible(true);
    }//GEN-LAST:event_trasladosMenuActionPerformed

    private void reportesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesMenuActionPerformed
       Reportes r = new Reportes();
       r.setVisible(true);
    }//GEN-LAST:event_reportesMenuActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bienesMenu;
    private javax.swing.JButton cesionButton;
    private javax.swing.JMenuItem inventarioMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem reportesMenu;
    private javax.swing.JMenuItem trasladosMenu;
    private javax.swing.JMenuItem usuarioMenuItem;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Images/fondoGeneral.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
